inherit_from: .rubocop_todo.yml

Naming/AsciiIdentifiers:
  Exclude:
    - 'test/**/*'
    - 'docs/**/*'

Naming/MethodName:
  EnforcedStyle: snake_case
  Exclude:
    - 'test/**/*'
    - 'docs/**/*'

Metrics/BlockLength:
  Max: 62
  Exclude:
    - 'test/**/*'
    - 'docs/**/*'

Documentation:
  Enabled: false