---
- hosts: all
  become: yes
  vars_files:
    - ../vars/site.yml
  tasks:
    - name: install packages
      apt:
        name: "{{packages}}"
        update_cache: yes
      vars:
        packages:
        - build-essential
        - git
        - git-core
        - libssl-dev
        - libqt4-dev
        - libc6-dev
        - automake
        - libtool
        - libyaml-dev
        - zlib1g
        - zlib1g-dev
        - openssl
        - libssl-dev
        - libreadline-dev
        - libxml2-dev
        - libxslt1-dev
        - libncurses5-dev
        - pkg-config
        - chrpath
        - libfontconfig1-dev
        - libxft-dev

    - name: install rbenv
      git: repo=https://github.com/sstephenson/rbenv.git
           dest={{ home }}/.rbenv
           version=master

    - name: add rbenv path to bash_profile
      template:
        src: ../templates/rbenv.sh
        dest: /etc/profile.d/rbenv.sh
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: 0644

    - name: install ruby_build
      git: repo=https://github.com/sstephenson/ruby-build.git
           dest={{ home }}/.rbenv/plugins/ruby-build
           version=master

    - name: install ruby {{ ruby_version }} 
      shell: "export RBENV_ROOT={{ home }}/.rbenv; export PATH=$RBENV_ROOT/bin:$PATH; echo N | rbenv install {{ ruby_version }}; rbenv global {{ ruby_version }}"
      args:
        creates: "{{ home }}/.rbenv/versions/{{ ruby_version }}/"

    - name: install bundler
      shell: "{{ home }}/.rbenv/shims/gem install bundler"
      args:
        creates: "{{ home }}/.rbenv/shims/bundle"

    - name: change ~/.rbenv owner to {{ user }}
      file: path={{ home }}/.rbenv state=directory owner={{ user }} group={{ user }} recurse=yes

    - name: install nvm
      git: repo=https://github.com/nvm-sh/nvm.git
           dest={{ home }}/.nvm
           version=master

    - name: add nvm path to bash_profile
      copy: src=../files/nvm.sh dest=/etc/profile.d/nvm.sh

    - name: change ~/.nvm owner to {{ user }}
      file: path={{ home }}/.nvm state=directory owner={{ user }} group={{ user }} recurse=yes